name: Build and Deploy amCharts 5 Examples to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build amCharts 5 examples
        run: |
          npm run build
          npm run build:examples || echo "No build:examples script, examples built in main"

      - name: List dist folder contents for debugging
        run: |
          echo "Listing dist folder contents:"
          ls -R ./dist || echo "dist folder not found"

      - name: List examples folder contents for debugging
        run: |
          echo "Listing dist/examples folder contents:"
          ls -R ./dist/examples || echo "dist/examples folder not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/examples
